import 'package:laferia/core/models/models.dart';

class TiendaService {
  static final List<Tienda> obtenerTiendas = [
    Tienda(
      id: '1',
      nombre: 'Comedor La Paz',
      nombrePropietario: 'Juan Pérez',
      ubicacion: Ubicacion(lat: -16.4943, lng: -68.1710),
      rubroPrincipal: 'comida',
      categoriaId: '1',
      subcategoriaId: '1',
      productos: ['1', '2', '3'],
      contacto: Contacto(telefono: '123456789'),
      direccion: 'Av. Principal 123',
      diasAtencion: ['Lunes', 'Martes', 'Miércoles'],
      horarioAtencion: '08:00 - 20:00',
      horario: '08:00 - 20:00',
      calificacion: 4.5,
    ),
    Tienda(
      id: '2',
      nombre: 'Tienda de Ropa Fashion',
      nombrePropietario: 'Ana Gómez',
      ubicacion: Ubicacion(lat: -16.4950, lng: -68.1705),
      rubroPrincipal: 'ropa',
      categoriaId: '2',
      subcategoriaId: '2',
      productos: ['4', '5'],
      contacto: Contacto(telefono: '987654321'),
      direccion: 'Calle Secundaria 456',
      diasAtencion: ['Martes', 'Miércoles', 'Jueves'],
      horarioAtencion: '10:00 - 19:00',
      horario: '10:00 - 19:00',
      calificacion: 4.0,
    ),
    Tienda(
      id: '3',
      nombre: 'Ropa deportiva El Saber',
      nombrePropietario: 'Carlos López',
      ubicacion: Ubicacion(lat: -16.4930, lng: -68.1720),
      rubroPrincipal: 'deporte',
      categoriaId: '3',
      subcategoriaId: '3',
      productos: ['6', '7', '8'],
      contacto: Contacto(telefono: '456789123'),
      direccion: 'Av. Cultura 789',
      diasAtencion: ['Lunes', 'Miércoles', 'Viernes'],
      horarioAtencion: '09:00 - 18:00',
      horario: '09:00 - 18:00',
      calificacion: 4.8,
    ),
    Tienda(
      id: '4',
      nombre: 'Celulares Dulces Sabores',
      nombrePropietario: 'María Fernández',
      ubicacion: Ubicacion(lat: -16.4960, lng: -68.1730),
      rubroPrincipal: 'tecnología',
      categoriaId: '4',
      subcategoriaId: '4',
      productos: ['9', '10'],
      contacto: Contacto(telefono: '321654987'),
      direccion: 'Calle Panaderos 321',
      diasAtencion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
      horarioAtencion: '06:00 - 14:00',
      horario: '06:00 - 14:00', // Mantener por compatibilidad
      calificacion: 4.2,
    ),
    Tienda(
      id: '5',
      nombre: 'Farmacia Todo en Uno',
      nombrePropietario: 'Pedro Martínez',
      ubicacion: Ubicacion(lat: -16.4970, lng: -68.1740),
      rubroPrincipal: 'salud',
      categoriaId: '5',
      subcategoriaId: '5',
      productos: ['11', '12', '13'],
      contacto: Contacto(telefono: '654321987'),
      direccion: 'Av. Ferreteros 654',
      diasAtencion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
      horarioAtencion: '07:00 - 17:00',
      horario: '07:00 - 17:00', // Mantener por compatibilidad
      calificacion: 4.6,
    ),
    Tienda(
      id: '6',
      nombre: 'Automotivos La Paz',
      nombrePropietario: 'Laura Torres',
      ubicacion: Ubicacion(lat: -16.4980, lng: -68.1750),
      rubroPrincipal: 'auto',
      categoriaId: '6',
      subcategoriaId: '6',
      productos: ['14', '15'],
      contacto: Contacto(telefono: '789123456'),
      direccion: 'Calle Electrónica 987',
      diasAtencion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
      horarioAtencion: '09:00 - 20:00',
      horario: '09:00 - 20:00', // Mantener por compatibilidad
      calificacion: 4.3,
    ),
    Tienda(
      id: '7',
      nombre: 'Joyería Brillantes',
      nombrePropietario: 'Sofía Ruiz',
      ubicacion: Ubicacion(lat: -16.4990, lng: -68.1760),
      rubroPrincipal: 'joya',
      categoriaId: '7',
      subcategoriaId: '7',
      productos: ['16', '17'],
      contacto: Contacto(telefono: '123789456'),
      direccion: 'Av. Joyeros 123',
      diasAtencion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
      horarioAtencion: '10:00 - 19:00',
      horario: '10:00 - 19:00', // Mantener por compatibilidad
      calificacion: 4.7,
    ),
  ];
}
